First round of release, tests are still missing.
eatfirst/Flask-Click-Migrate pull request #1
Opened 2016-08-19 21:44 UTC by jaysonsantos

This is just a initial release of the open sourced version.
@pedro-teixeira Could you create a travis job for this project? When you do it I will add a travis.yml for it.
I still have to figure out a good way to test it.

2016-08-20 09:07 UTC, pedro-teixeira commented
@jaysonsantos: https://travis-ci.org/eatfirst/Flask-Click-Migrate/

Please let me know when to create an account on PyPi or any other service so we have all using a central account.

2016-08-30 09:14 UTC, pedro-teixeira commented
@jaysonsantos what is the status here?

2016-08-31 11:54 UTC, jaysonsantos commented
I didn't work on it anymore, probably I will do it next week.

2017-01-12 09:19 UTC, pedro-teixeira requested changes

2017-01-12 09:19 UTC, pedro-teixeira commented on .travis.yml
> +  - "3.5"
Why not `3.6`?

2017-01-12 09:19 UTC, pedro-teixeira commented on setup.py
> +    author='Eat First gmbh',
Please change to `EatFirst.com`

2017-01-12 09:20 UTC, pedro-teixeira commented
Please fix the `README` file to have the proper copyright.

2017-01-12 12:00 UTC, andreoliwa commented on requirements_test.txt
> +flake8
Shouldn't we pin the versions, even for testing?

2017-01-12 12:00 UTC, andreoliwa commented on setup.py
> +        'Programming Language :: Python :: 3',
"3.4" and "3.5", no?
According to the travis.yml file above.

2017-01-13 16:30 UTC, pedro-teixeira approved these changes

2017-01-13 17:21 UTC, andreoliwa approved these changes

2017-01-16 09:01 UTC, merged